FROM php:7.4-cli
COPY . C:/Users/Dilan/OneDrive/Desktop/Internet Programming/GIT REPOS/CSYM019/Week 10
WORKDIR C:/Users/Dilan/OneDrive/Desktop/Internet Programming/GIT REPOS/CSYM019/Week 10
CMD [ "php", "./week10.php" ]